# Generated by Django 3.2.4 on 2021-06-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auto_20210615_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dt_down',
            new_name='dt_closed',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='dt_up',
            new_name='dt_live',
        ),
    ]
