# Generated by Django 3.2.4 on 2021-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auto_20210615_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='winning_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='winning_price',
            field=models.FloatField(max_length=0, null=True),
        ),
    ]
