# Generated by Django 3.2.4 on 2021-06-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_alter_item_winning_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='promiser',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
