# Generated by Django 3.2.4 on 2021-06-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='live',
        ),
    ]
