# Generated by Django 3.2.4 on 2021-06-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0009_bid_dt_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='winners_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
