# Generated by Django 3.2.4 on 2021-06-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0011_alter_item_winners_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='phone_number',
            field=models.CharField(default='07000000000', max_length=20),
            preserve_default=False,
        ),
    ]
