# Generated by Django 3.2.4 on 2021-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0012_bid_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='winning_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
