# Generated by Django 4.0.5 on 2022-06-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0013_item_winning_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('auction_name', models.CharField(default='Promise Auction Bidding System', max_length=500)),
                ('is_promise_auction', models.BooleanField(default=True, verbose_name='Is this a promise auction (as opposed to a conventional auction)?')),
                ('payment_account_holder_name', models.CharField(blank=True, help_text='Used in the message generator.', max_length=100, null=True)),
                ('payment_account_number', models.CharField(blank=True, help_text='Used in the message generator.', max_length=8, null=True)),
                ('payment_sort_code', models.CharField(blank=True, help_text='Used in the message generator.', max_length=8, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Used in the message generator.', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionDescriptionBulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='After the auction, you will be contacted with any promises that you have won.', help_text='The bullet points are displayed at the top of the bidding page. You may want to mention where the money raised will go going, the process to redeeming items, etc.', max_length=500)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.auctionsetting')),
            ],
        ),
    ]
