# Generated by Django 4.0.5 on 2022-06-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0014_auctionsetting_auctiondescriptionbulletpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctiondescriptionbulletpoint',
            options={'ordering': ('loc', 'id')},
        ),
        migrations.AlterModelOptions(
            name='auctionsetting',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='auctiondescriptionbulletpoint',
            name='loc',
            field=models.IntegerField(default=0, help_text='Denotes the order that the bullet point appear compared to others.'),
        ),
    ]
