# Generated by Django 4.0.5 on 2022-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0016_alter_auctionsetting_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsetting',
            name='max_bid',
            field=models.DecimalField(decimal_places=2, default=999.99, help_text='The highest bid someone can make on this auction.', max_digits=12),
        ),
        migrations.AddField(
            model_name='auctionsetting',
            name='primary_colour',
            field=models.CharField(default='#000080', help_text='Hex code. Used for some text on the website.', max_length=7),
        ),
    ]
