# Generated by Django 4.0.5 on 2022-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0017_auctionsetting_max_bid_auctionsetting_primary_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsetting',
            name='enable_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auctionsetting',
            name='leaderboard_spaces',
            field=models.IntegerField(blank=True, default=10, help_text='The top X bidders to appear on the leaderboard. Leave blank to display all bidders on the leaderboard.', null=True),
        ),
    ]
