# Generated by Django 4.0.5 on 2022-06-17 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0018_auctionsetting_enable_leaderboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsetting',
            name='bid_sync_regularity',
            field=models.IntegerField(default=10, help_text='How often the winning bids on the bidding page are synced with the server (in seconds).'),
        ),
        migrations.AddField(
            model_name='item',
            name='dt_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 28, 58, 464900, tzinfo=utc), verbose_name='date/time last updated'),
            preserve_default=False,
        ),
    ]
