# Generated by Django 4.2.1 on 2024-09-29 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0020_alter_bid_options_remove_item_dt_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsetting',
            name='prevent_decimals',
            field=models.BooleanField(default=False, help_text='If ticked, bids must be whole numbers.'),
        ),
        migrations.AlterField(
            model_name='auctionsetting',
            name='bid_sync_regularity',
            field=models.IntegerField(default=10, help_text='How often the winning bids on the bidding page are synced with the server (in seconds, minimum 5). Increase this to improve performance.', validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
